import { pgTable, text, serial, integer, boolean, timestamp, pgEnum, foreignKey, uniqueIndex, jsonb } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";
import { relations } from "drizzle-orm";

// Enum for project color themes
export const colorThemeEnum = pgEnum('color_theme', [
  'blue', 'green', 'red', 'purple', 'orange', 'teal', 'indigo', 'yellow', 'pink', 'gray'
]);

// Enum for team member roles
export const teamRoleEnum = pgEnum('team_role', [
  'owner', 'editor', 'viewer'
]);

// Enum for user roles
export const userRoleEnum = pgEnum('user_role', [
  'user', 'vip', 'unlimited', 'admin'
]);

export const responseStyleEnum = pgEnum('response_style', [
  'concise', 'detailed', 'balanced'
]);

// Enum for AI providers
export const aiProviderEnum = pgEnum('ai_provider', [
  'openai', 'google', 'azure'
]);

// Enum for embed styles
export const embedStyleEnum = pgEnum('embed_style', [
  'classic', 'advanced', 'premium', 'minimalist'
]);

// Users table
export const users = pgTable("users", {
  id: serial("id").primaryKey(),
  email: text("email").notNull().unique(),
  username: text("username").notNull().unique(),
  password: text("password").notNull(),
  role: userRoleEnum("role").notNull().default('user'),
  isActive: boolean("is_active").notNull().default(false),
  activationToken: text("activation_token"),
  resetPasswordToken: text("reset_password_token"),
  resetPasswordExpires: timestamp("reset_password_expires"),
  darkMode: boolean("dark_mode").notNull().default(false),
  lastLogin: timestamp("last_login"),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Projects table
export const projects = pgTable("projects", {
  id: serial("id").primaryKey(),
  name: text("name").notNull(),
  colorTheme: colorThemeEnum("color_theme").notNull().default('blue'),
  defaultPrompt: text("default_prompt").default("You are a helpful AI assistant."),
  embedToken: text("embed_token"),
  anthropicApiKey: text("anthropic_api_key"),
  openaiApiKey: text("openai_api_key"),
  googleApiKey: text("google_api_key"), // API key for Google Generative AI
  aiProvider: aiProviderEnum("ai_provider").default("openai"),
  aiModel: text("ai_model").default("gpt-4"), // Model selected from the provider
  azureEndpoint: text("azure_endpoint"), // URL pro Azure OpenAI endpoint
  createdAt: timestamp("created_at").defaultNow().notNull(),
  ownerId: integer("owner_id").references(() => users.id, { onDelete: 'cascade' }).notNull(),
  // New columns for customising the embedded chat
  chatbotName: text("chatbot_name").default("DocuSage Asistent"), // Custom chatbot name
  welcomeMessage: text("welcome_message").default("Hi, feel free to ask a question here"), // Custom welcome message
  // Notification columns
  notificationEnabled: boolean("notification_enabled").default(false), // Enables notifications
  notificationDelay: integer("notification_delay").default(15), // Delay in seconds before the notification appears
  notificationText: text("notification_text").default("Need help with anything?"), // Notification text
  // New columns for the API functionality
  apiKey: text("api_key"), // API key for accessing the project's API
  apiEnabled: boolean("api_enabled").default(false), // Je API povoleno pro tento projekt
  apiRateLimit: integer("api_rate_limit").default(100), // Number of API calls allowed per day (default: 100)
  // Embed style selection
  embedStyle: embedStyleEnum("embed_style").default("classic"), // Embed style selection
  // Embed disclaimer text
  embedDisclaimer: text("embed_disclaimer").default("Answers are generated by AI and may not always be accurate"), // Custom disclaimer text
  hidePoweredBy: boolean("hide_powered_by").default(false), // Option to hide the "Powered by" text
  // Bot icon for embed chat
  botIconUrl: text("bot_icon_url"), // URL cesta k ikonke bota pre embed chat
  // Rating system configuration
  ratingEnabled: boolean("rating_enabled").default(true), // Enables conversation rating
  ratingPromptMessage: text("rating_prompt_message").default("Please rate our conversation"), // Prompt message for the rating
  ratingThankYouMessage: text("rating_thank_you_message").default("Thank you for your rating!"), // Thank-you message for the rating
});

// Team members table for project collaboration
export const teamMembers = pgTable("team_members", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").references(() => projects.id, { onDelete: 'cascade' }).notNull(),
  userId: integer("user_id").references(() => users.id, { onDelete: 'cascade' }).notNull(),
  role: teamRoleEnum("role").notNull().default('editor'),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, (table) => {
  return {
    uniqueUserProject: uniqueIndex("unique_user_project").on(table.projectId, table.userId),
  };
});

// Global team members table for user collaboration
export const globalTeamMembers = pgTable("global_team_members", {
  id: serial("id").primaryKey(),
  ownerId: integer("owner_id").references(() => users.id, { onDelete: 'cascade' }).notNull(),
  memberId: integer("member_id").references(() => users.id, { onDelete: 'cascade' }).notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, (table) => {
  return {
    uniqueOwnerMember: uniqueIndex("unique_owner_member").on(table.ownerId, table.memberId),
  };
});

// PDFs table
export const pdfs = pgTable("pdfs", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").references(() => projects.id, { onDelete: 'cascade' }).notNull(),
  filename: text("filename").notNull(), // Original file name (shown to the user)
  storagePath: text("storage_path"), // File name on disk inside the pdfs/<projectId>/ folder
  content: text("content").notNull(), // Extracted text content
  uploadedById: integer("uploaded_by_id").references(() => users.id, { onDelete: 'set null' }),
  totalPages: integer("total_pages"),
  fileSize: integer("file_size"), // In bytes
  processingStatus: text("processing_status").default("pending"), // pending, processing, completed, failed
  processingError: text("processing_error"),
  weight: integer("weight").default(1).notNull(), // Source weight for search (1-10)
  createdAt: timestamp("created_at").defaultNow().notNull(),
  processedAt: timestamp("processed_at"),
});

// Processed documents table - for storing pre-analyzed content by the AI model
export const processedDocuments = pgTable("processed_documents", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").references(() => projects.id, { onDelete: 'cascade' }).notNull(),
  pdfId: integer("pdf_id").references(() => pdfs.id, { onDelete: 'cascade' }).notNull(),
  title: text("title"), // Extracted document title
  content: text("content"), // Content (deprecated - kept only for backward compatibility)
  type: text("type"), // Type (deprecated - kept only for backward compatibility)
  createdAt: timestamp("createdAt").defaultNow(), // Creation timestamp
  summary: text("summary"), // AI-generated document summary
  chunks: jsonb("chunks").notNull(), // Processed document parts stored as JSON
  metadata: jsonb("metadata"), // Additional document metadata (author, publication date, keywords)
  embeddings: jsonb("embeddings"), // Vector representations of the chunks for fast search
  processingType: text("processing_type").notNull().default("basic"), // Processing type (basic, advanced)
  processingDate: timestamp("processing_date").defaultNow().notNull(),
});

// Chat sessions table
export const chatSessions = pgTable("chat_sessions", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").references(() => projects.id, { onDelete: 'cascade' }).notNull(),
  visitorId: text("visitor_id").notNull(), // Unique identifier for website visitors
  createdAt: timestamp("created_at").defaultNow().notNull(),
  lastActiveAt: timestamp("last_active_at").defaultNow().notNull(),
  rating: integer("rating"), // Conversation rating, 1-5 stars
  ratedAt: timestamp("rated_at"), // Time of the rating
});

// Chat messages table
export const chatMessages = pgTable("chat_messages", {
  id: serial("id").primaryKey(),
  sessionId: integer("session_id").references(() => chatSessions.id, { onDelete: 'cascade' }).notNull(),
  content: text("content").notNull(),
  isFromUser: boolean("is_from_user").notNull(),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Table for tracking API calls
export const apiCalls = pgTable("api_calls", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").references(() => projects.id, { onDelete: 'cascade' }).notNull(),
  endpoint: text("endpoint").notNull(), // Which endpoint was called (e.g. "chat", "query")
  method: text("method").notNull(), // HTTP metoda (GET, POST)
  requestData: jsonb("request_data"), // Request data
  responseData: jsonb("response_data"), // Response data
  statusCode: integer("status_code").notNull(), // HTTP status code of the response
  responseTime: integer("response_time"), // Processing time in ms
  ipAddress: text("ip_address"), // IP adresa klienta
  userAgent: text("user_agent"), // User agent klienta
  createdAt: timestamp("created_at").defaultNow().notNull(), // Time of the call
  success: boolean("success").notNull().default(true), // Was the call successful?
  errorMessage: text("error_message"), // Optional error message
});

// Table for tracking topics (query categories)
export const queryTopics = pgTable("query_topics", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").references(() => projects.id, { onDelete: 'cascade' }).notNull(),
  name: text("name").notNull(), // Name of the topic/category
  count: integer("count").notNull().default(1), // Number of queries in this topic
  lastQueried: timestamp("last_queried").defaultNow().notNull(), // When the topic was last queried
  createdAt: timestamp("created_at").defaultNow().notNull(), // When the topic was first detected
});

// Table mapping queries to topics
export const queryToTopics = pgTable("query_to_topics", {
  id: serial("id").primaryKey(),
  topicId: integer("topic_id").references(() => queryTopics.id, { onDelete: 'cascade' }).notNull(),
  messageId: integer("message_id").references(() => chatMessages.id, { onDelete: 'cascade' }).notNull(),
  confidence: integer("confidence").notNull().default(100), // Classification confidence (0-100%)
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, (table) => {
  return {
    uniqueMessageTopic: uniqueIndex("unique_message_topic").on(table.messageId, table.topicId),
  };
});

// Document chunks table - enhanced for advanced processing
export const documentChunks = pgTable("document_chunks", {
  id: serial("id").primaryKey(),
  pdfId: integer("pdf_id").references(() => pdfs.id, { onDelete: 'cascade' }).notNull(),
  projectId: integer("project_id").references(() => projects.id, { onDelete: 'cascade' }).notNull(),
  chunkIndex: integer("chunk_index").notNull(),
  content: text("content").notNull(), // Text content of the chunk (500-1000 tokens)
  embedding: jsonb("embedding"), // Vector representation for semantic search
  pageRange: text("page_range"), // Page range (e.g. "5-7")
  topic: text("topic"), // Keywords/topic of the chunk
  tokenCount: integer("token_count"), // Number of tokens in the chunk
  overlap: text("overlap"), // Part overlapping with the previous chunk
  keywords: jsonb("keywords"), // Extracted keywords
  summary: text("summary"), // Short summary of the chunk
  contextType: text("context_type").default("general"), // kapitola, sekce, tabulka, seznam
  confidence: integer("confidence").default(100), // Confidence in the split being correct (0-100)
  createdAt: timestamp("created_at").defaultNow().notNull(),
  processedAt: timestamp("processed_at").defaultNow().notNull(),
});

// Vector search optimization table
export const vectorSearchIndex = pgTable("vector_search_index", {
  id: serial("id").primaryKey(),
  chunkId: integer("chunk_id").references(() => documentChunks.id, { onDelete: 'cascade' }).notNull(),
  projectId: integer("project_id").references(() => projects.id, { onDelete: 'cascade' }).notNull(),
  searchVector: jsonb("search_vector").notNull(), // Optimalized vector for search
  lastUsed: timestamp("last_used").defaultNow(),
  accessCount: integer("access_count").default(0),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Query performance tracking
export const queryPerformance = pgTable("query_performance", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").references(() => projects.id, { onDelete: 'cascade' }).notNull(),
  query: text("query").notNull(),
  chunksFound: integer("chunks_found"),
  searchTime: integer("search_time"), // milliseconds
  responseTime: integer("response_time"), // milliseconds
  relevanceScore: integer("relevance_score"), // 0-100
  userSatisfaction: integer("user_satisfaction"), // 1-5 if provided
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Failed responses tracking for admin notifications
export const failedResponses = pgTable("failed_responses", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").references(() => projects.id, { onDelete: 'cascade' }).notNull(),
  sessionId: integer("session_id").references(() => chatSessions.id, { onDelete: 'cascade' }),
  userQuery: text("user_query").notNull(),
  aiResponse: text("ai_response").notNull(),
  failureReason: text("failure_reason").notNull(), // "no_relevant_chunks", "insufficient_context", "technical_error"
  chunksFound: integer("chunks_found").default(0),
  documentsSearched: integer("documents_searched").default(0),
  isResolved: boolean("is_resolved").default(false).notNull(),
  adminNotes: text("admin_notes"),
  resolvedAt: timestamp("resolved_at"),
  resolvedBy: integer("resolved_by").references(() => users.id, { onDelete: 'set null' }),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

// Backwards compatibility - keeping old table name for existing code
export const pdfChunks = documentChunks;

// User activity tracking for collaboration indicators
export const userActivity = pgTable("user_activity", {
  id: serial("id").primaryKey(),
  userId: integer("user_id").references(() => users.id, { onDelete: 'cascade' }).notNull(),
  projectId: integer("project_id").references(() => projects.id, { onDelete: 'cascade' }).notNull(),
  lastActivity: timestamp("last_activity").defaultNow().notNull(),
  activityType: text("activity_type").notNull().default("viewing"), // viewing, editing, chatting
  isActive: boolean("is_active").default(true).notNull(),
  sessionId: text("session_id"), // Browser session identifier
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
}, (table) => {
  return {
    uniqueUserProject: uniqueIndex("unique_user_project_session").on(table.userId, table.projectId, table.sessionId),
  };
});

// Training options table for project customization (temporarily without AI features)
export const trainingOptions = pgTable("training_options", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").references(() => projects.id, { onDelete: 'cascade' }).notNull().unique(),
  contextSize: integer("context_size").notNull().default(1500),
  responseStyle: responseStyleEnum("response_style").notNull().default('balanced'),
  customPromptTemplate: text("custom_prompt_template"),
  useKeywordsExtraction: boolean("use_keywords_extraction").notNull().default(true),
  useSemanticSearch: boolean("use_semantic_search").notNull().default(true),
  maxDocuments: integer("max_documents").notNull().default(10),
  documentChunkSize: integer("document_chunk_size").notNull().default(1000),
  enableCitationGeneration: boolean("enable_citation_generation").notNull().default(false),
  temperatureValue: integer("temperature_value").notNull().default(5), // Store as integer, divide by 10 when using
  customStopWords: text("custom_stop_words"),
  // Removed: conversationalMode: boolean - no longer supported
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

// Define relations
// Global team members relations
export const globalTeamMembersRelations = relations(globalTeamMembers, ({ one }) => ({
  owner: one(users, {
    fields: [globalTeamMembers.ownerId],
    references: [users.id],
  }),
  member: one(users, {
    fields: [globalTeamMembers.memberId],
    references: [users.id],
  }),
}));

export const usersRelations = relations(users, ({ many }) => ({
  ownedProjects: many(projects),
  teamMemberships: many(teamMembers),
  uploadedPdfs: many(pdfs),
  ownedTeamMembers: many(globalTeamMembers, { relationName: "owner" }),
  memberOfTeams: many(globalTeamMembers, { relationName: "member" }),
}));

export const projectsRelations = relations(projects, ({ one, many }) => ({
  owner: one(users, {
    fields: [projects.ownerId],
    references: [users.id],
  }),
  teamMembers: many(teamMembers),
  pdfs: many(pdfs),
  chatSessions: many(chatSessions),
  apiCalls: many(apiCalls),
  queryTopics: many(queryTopics),
  chatbotAnalytics: many(chatbotAnalytics),
  pdfChunks: many(pdfChunks),
  failedResponses: many(failedResponses),
  trainingOptions: one(trainingOptions, {
    fields: [projects.id],
    references: [trainingOptions.projectId],
  }),
}));

export const trainingOptionsRelations = relations(trainingOptions, ({ one }) => ({
  project: one(projects, {
    fields: [trainingOptions.projectId],
    references: [projects.id],
  }),
}));

export const failedResponsesRelations = relations(failedResponses, ({ one }) => ({
  project: one(projects, {
    fields: [failedResponses.projectId],
    references: [projects.id],
  }),
  session: one(chatSessions, {
    fields: [failedResponses.sessionId],
    references: [chatSessions.id],
  }),
  resolvedByUser: one(users, {
    fields: [failedResponses.resolvedBy],
    references: [users.id],
  }),
}));

export const teamMembersRelations = relations(teamMembers, ({ one }) => ({
  project: one(projects, {
    fields: [teamMembers.projectId],
    references: [projects.id],
  }),
  user: one(users, {
    fields: [teamMembers.userId],
    references: [users.id],
  }),
}));

export const pdfsRelations = relations(pdfs, ({ one, many }) => ({
  project: one(projects, {
    fields: [pdfs.projectId],
    references: [projects.id],
  }),
  uploadedBy: one(users, {
    fields: [pdfs.uploadedById],
    references: [users.id],
  }),
  processedVersions: many(processedDocuments),
  chunks: many(pdfChunks)
}));

export const processedDocumentsRelations = relations(processedDocuments, ({ one }) => ({
  project: one(projects, {
    fields: [processedDocuments.projectId],
    references: [projects.id],
  }),
  pdf: one(pdfs, {
    fields: [processedDocuments.pdfId],
    references: [pdfs.id], 
  }),
}));

export const pdfChunksRelations = relations(pdfChunks, ({ one }) => ({
  project: one(projects, {
    fields: [pdfChunks.projectId],
    references: [projects.id],
  }),
  pdf: one(pdfs, {
    fields: [pdfChunks.pdfId],
    references: [pdfs.id], 
  }),
}));

export const chatSessionsRelations = relations(chatSessions, ({ one, many }) => ({
  project: one(projects, {
    fields: [chatSessions.projectId],
    references: [projects.id],
  }),
  messages: many(chatMessages),
}));

export const chatMessagesRelations = relations(chatMessages, ({ one }) => ({
  session: one(chatSessions, {
    fields: [chatMessages.sessionId],
    references: [chatSessions.id],
  }),
}));

export const apiCallsRelations = relations(apiCalls, ({ one }) => ({
  project: one(projects, {
    fields: [apiCalls.projectId],
    references: [projects.id],
  }),
}));

export const queryTopicsRelations = relations(queryTopics, ({ one, many }) => ({
  project: one(projects, {
    fields: [queryTopics.projectId],
    references: [projects.id],
  }),
  mappings: many(queryToTopics),
}));

export const queryToTopicsRelations = relations(queryToTopics, ({ one }) => ({
  topic: one(queryTopics, {
    fields: [queryToTopics.topicId],
    references: [queryTopics.id],
  }),
  message: one(chatMessages, {
    fields: [queryToTopics.messageId],
    references: [chatMessages.id],
  }),
}));

// Create insert schemas with Zod validation
export const insertUserSchema = createInsertSchema(users)
  .extend({
    email: z.string().email({ message: 'Please enter a valid email address' }),
    password: z.string().min(6, { message: 'The password must be at least 6 characters long' }),
    captchaToken: z.string().min(1, { message: 'Please confirm that you are not a robot' }).optional(),
  })
  .omit({ 
    id: true, 
    createdAt: true, 
    lastLogin: true, 
    // isActive removed from omit so it can be set explicitly during registration
    activationToken: true,
    resetPasswordToken: true,
    resetPasswordExpires: true
  });

export const insertProjectSchema = createInsertSchema(projects)
  .omit({ id: true, createdAt: true, ownerId: true });

export const insertTeamMemberSchema = createInsertSchema(teamMembers)
  .omit({ id: true, createdAt: true });

export const insertGlobalTeamMemberSchema = createInsertSchema(globalTeamMembers)
  .omit({ id: true, createdAt: true });

export const insertPdfSchema = createInsertSchema(pdfs)
  .omit({ id: true, createdAt: true, content: true });

export const insertChatSessionSchema = createInsertSchema(chatSessions)
  .omit({ id: true, createdAt: true, lastActiveAt: true });

export const insertChatMessageSchema = createInsertSchema(chatMessages)
  .omit({ id: true, createdAt: true });

export const insertTrainingOptionsSchema = createInsertSchema(trainingOptions)
  .omit({ id: true, updatedAt: true });

export const insertProcessedDocumentSchema = createInsertSchema(processedDocuments)
  .omit({ id: true, processingDate: true, createdAt: true });

export const insertApiCallSchema = createInsertSchema(apiCalls)
  .omit({ id: true, createdAt: true });

export const insertQueryTopicSchema = createInsertSchema(queryTopics)
  .omit({ id: true, createdAt: true, lastQueried: true, count: true });

export const insertQueryToTopicSchema = createInsertSchema(queryToTopics)
  .omit({ id: true, createdAt: true });

export const insertPdfChunkSchema = createInsertSchema(pdfChunks)
  .omit({ id: true, createdAt: true });

export const insertUserActivitySchema = createInsertSchema(userActivity)
  .omit({ id: true, createdAt: true, updatedAt: true });

// Export types
export type User = typeof users.$inferSelect;
export type InsertUser = z.infer<typeof insertUserSchema>;

export type ApiCall = typeof apiCalls.$inferSelect;
export type InsertApiCall = z.infer<typeof insertApiCallSchema>;

export type Project = typeof projects.$inferSelect;
export type InsertProject = z.infer<typeof insertProjectSchema>;

export type TeamMember = typeof teamMembers.$inferSelect;
export type InsertTeamMember = z.infer<typeof insertTeamMemberSchema>;
export type GlobalTeamMember = typeof globalTeamMembers.$inferSelect;
export type InsertGlobalTeamMember = z.infer<typeof insertGlobalTeamMemberSchema>;

export type Pdf = typeof pdfs.$inferSelect;
export type InsertPdf = z.infer<typeof insertPdfSchema>;

export type ChatSession = typeof chatSessions.$inferSelect;
export type InsertChatSession = z.infer<typeof insertChatSessionSchema>;

export type ChatMessage = typeof chatMessages.$inferSelect;
export type InsertChatMessage = z.infer<typeof insertChatMessageSchema>;

export type TrainingOption = typeof trainingOptions.$inferSelect;
export type InsertTrainingOption = z.infer<typeof insertTrainingOptionsSchema>;

export type UserActivity = typeof userActivity.$inferSelect;
export type InsertUserActivity = z.infer<typeof insertUserActivitySchema>;

export type ProcessedDocument = typeof processedDocuments.$inferSelect;
export type InsertProcessedDocument = z.infer<typeof insertProcessedDocumentSchema>;

export type QueryTopic = typeof queryTopics.$inferSelect;
export type InsertQueryTopic = z.infer<typeof insertQueryTopicSchema>;

export type QueryToTopic = typeof queryToTopics.$inferSelect;
export type InsertQueryToTopic = z.infer<typeof insertQueryToTopicSchema>;

/** Response of POST /api/register */
export interface RegistrationResponse {
  id: number;
  username: string;
  email: string;
  /** true = the account is awaiting email activation */
  verificationRequired: boolean;
  message?: string;
  /** The account was created, but the activation email could not be sent. */
  emailFailed?: boolean;
  /** Activation was skipped (development environment). */
  manualActivation?: boolean;
}

export type PdfChunk = typeof pdfChunks.$inferSelect;
export type InsertPdfChunk = z.infer<typeof insertPdfChunkSchema>;

// New table for chatbot analytics - records chat interactions
export const chatbotAnalytics = pgTable("chatbot_analytics", {
  id: serial("id").primaryKey(),
  projectId: integer("project_id").references(() => projects.id, { onDelete: 'cascade' }).notNull(),
  pageUrl: text("page_url"), // URL of the page where the chat was opened
  referrer: text("referrer"), // Referring page
  action: text("action").notNull(), // Typ akce: "open", "query", "close"
  visitorId: text("visitor_id").notNull(), // Visitor ID
  sessionId: text("session_id"), // ID relace
  userAgent: text("user_agent"), // Browser user agent
  ipAddress: text("ip_address"), // IP adresa (pokud je povoleno)
  duration: integer("duration"), // Interaction duration in seconds (for open chats)
  deviceType: text("device_type"), // desktop, mobile, tablet
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const chatbotAnalyticsRelations = relations(chatbotAnalytics, ({ one }) => ({
  project: one(projects, {
    fields: [chatbotAnalytics.projectId],
    references: [projects.id],
  }),
}));

export const insertChatbotAnalyticsSchema = createInsertSchema(chatbotAnalytics)
  .omit({ id: true, createdAt: true });

export type ChatbotAnalytics = typeof chatbotAnalytics.$inferSelect;
export type InsertChatbotAnalytics = z.infer<typeof insertChatbotAnalyticsSchema>;

// Custom type for the training options form (currently without AI features)
export interface ProjectTrainingOptions {
  contextSize: number;
  responseStyle: "concise" | "detailed" | "balanced";
  customPromptTemplate?: string;
  useKeywordsExtraction: boolean;
  useSemanticSearch: boolean;
  maxDocuments: number;
  documentChunkSize: number;
  enableCitationGeneration: boolean;
  temperatureValue: number; // Represented as 0-1 in UI, stored as 0-10 in DB
  customStopWords?: string;
  // Removed: conversationalMode: boolean - no longer supported
}
